name = "citycoins"
account_id = '6f54e90da6d1b280fe00a153cb394c68'
type = 'webpack'
workers_dev = true
# target_type = "webpack"

[site]
bucket = './'
entry-point = "workers-site"

[env.production]
route = '*citycoins.co/*'
zone_id = '3e5041a8cc83842af0c2734fe6b33adc'
